# Generated by Django 4.1.7 on 2023-03-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droll', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('review', models.IntegerField()),
                ('yrs', models.CharField(max_length=20)),
                ('mony', models.CharField(max_length=20)),
                ('loction', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
            ],
        ),
    ]
