# Generated by Django 4.1.7 on 2023-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
