# Generated by Django 4.1.7 on 2023-03-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0003_desc_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
