# Generated by Django 4.1.7 on 2023-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0005_alter_desc_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='day',
        ),
        migrations.AddField(
            model_name='desc',
            name='days',
            field=models.IntegerField(default=5),
        ),
    ]
