# Generated by Django 4.1.7 on 2023-03-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0006_remove_desc_day_desc_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='days',
        ),
    ]
