# Generated by Django 4.1.7 on 2023-03-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0010_remove_desc_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
